In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
import pandas as pd
import numpy as np

In [4]:
from pathlib import Path
home = str(Path.home())

In [5]:
import sys
sys.path.insert(0,"%s/rankability_toolbox_dev"%home)

In [6]:
import pyrankability

In [7]:
import copy
n = 4
D = np.ones((n,n))*np.NaN
for i in range(n):
    D[i,i]=0
offset = 0.
for i in range(n):
    for j in range(n):
        if i == j:
            continue
        def do_first(offset):
            missing_first = np.where(np.isnan(D[:,j]-D[:,i]))[0]
            for ix in missing_first:
                Dcopy = copy.copy(D)
                #Dcopy[j,j] = np.nan
                #Dcopy[i,i] = np.nan
                first = np.where(Dcopy[:,j]-Dcopy[:,i]<0)[0]
                not_first = np.where(Dcopy[:,j]-Dcopy[:,i]>0)[0]
                if len(not_first) > len(first):                    
                    if np.isnan(D[ix,j]) and np.isnan(D[ix,i]):
                        D[ix,j] = 1+offset
                        D[ix,i] = D[ix,j]+1+offset
                    elif np.isnan(D[ix,j]):
                        D[ix,j] = D[ix,i]-1+offset
                    else:
                        D[ix,i] = D[ix,j]+1+offset
                else:
                    if np.isnan(D[ix,i]) and np.isnan(D[ix,j]):
                        D[ix,i] = 1+offset
                        D[ix,j] = D[ix,i]+1+offset
                    elif np.isnan(D[ix,i]):
                        D[ix,i] = D[ix,j]-1+offset
                    else:
                        D[ix,j] = D[ix,i]+1+offset
                offset+=0.1
            return offset
        def do_second(offset):
            missing_second = np.where(np.isnan(D[i,:]-D[j,:]))[0]
            for ix in missing_second:
                Dcopy = copy.copy(D)
                #Dcopy[j,j] = np.nan
                #Dcopy[i,i] = np.nan
                second = np.where(Dcopy[i,:]-Dcopy[j,:]<0)[0]
                not_second = np.where(Dcopy[i,:]-Dcopy[j,:]>0)[0]
                if len(second) > len(not_second):                    
                    if np.isnan(D[j,ix]) and np.isnan(D[i,ix]):
                        D[j,ix] = 1+offset
                        D[i,ix] = D[j,ix]+1+offset
                    elif np.isnan(D[j,ix]):
                        D[j,ix] = D[i,ix]-1+offset
                    else:
                        D[i,ix] = D[j,ix]+1+offset
                else:
                    if np.isnan(D[i,ix]) and np.isnan(D[j,ix]):
                        D[i,ix] = 1+offset
                        D[j,ix] = D[i,ix]+1+offset
                    elif np.isnan(D[i,ix]):
                        D[i,ix] = D[j,ix]-1+offset
                    else:
                        D[j,ix] = D[i,ix]+1+offset  
                offset+=0.1
            return offset
        if len(np.where(np.isnan(D[i,:]-D[j,:]))[0]) < len(np.where(np.isnan(D[:,j]-D[:,i]))[0]):
            offset = do_first(offset)
            offset = do_second(offset)
        else:
            offset = do_second(offset)
            offset = do_first(offset)
        print(D)
D

[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  nan]
 [3.  1.5 nan 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]
[[0.  1.1 1.2 2.6]
 [1.  0.  2.4 1.3]
 [1.4 2.8 0.  2.2]
 [3.  1.5 2.7 0. ]]


array([[0. , 1.1, 1.2, 2.6],
       [1. , 0. , 2.4, 1.3],
       [1.4, 2.8, 0. , 2.2],
       [3. , 1.5, 2.7, 0. ]])

In [26]:
D = np.array([
    [0. , 1.1, 1.2, 2.6],
    [1. , 0. , 2.4, 1.3],
    [1.4, 2.8, 0. , 2.2],
    [3. , 1.5, 2.2, 0. ]])

In [29]:
pd.DataFrame(D)

0    1    2    3
0  0.0  1.1  1.2  2.6
1  1.0  0.0  2.4  1.3
2  1.4  2.8  0.0  2.2
3  3.0  1.5  2.2  0.0

In [32]:
C = pyrankability.construct.C_count(pd.DataFrame(D))
pd.DataFrame(C)

0    1    2    3
0  0.0  4.0  4.0  4.0
1  4.0  0.0  4.0  4.0
2  4.0  4.0  0.0  4.0
3  4.0  4.0  4.0  0.0

In [31]:
k,details = pyrankability.rank.solve(pd.DataFrame(D),method='hillside')
P = np.array(details['P'][0])
k,P

Using license file /opt/tljh/user/lib/python3.7/site-packages/gurobipy/.libs/gurobi.lic
Restricted license - for non-production use only - expires 2022-01-13


(24.0, array([3, 2, 1, 0]))

In [140]:
C.iloc[P,:].iloc[:,P]

3    2    1    0
3  0.0  4.0  3.0  4.0
2  4.0  0.0  4.0  4.0
1  5.0  4.0  0.0  4.0
0  4.0  4.0  4.0  0.0

In [143]:
pd.DataFrame(D).iloc[P,:].iloc[:,P]

3    2    1    0
3  0.0  2.7  1.5  3.0
2  2.2  0.0  2.8  1.4
1  1.3  2.4  0.0  1.0
0  2.6  1.2  1.1  0.0

In [10]:
D_str = """
1.0,2.0,3.0,4.0
0.9,1.9,2.9,3.9
0.8,1.8,2.8,3.8
0.7,1.7,2.7,3.7
"""
D = []
for line in D_str.strip().split("\n"):
    D.append([float(v) for v in line.split(",")])
D = pd.DataFrame(D)
D

0    1    2    3
0  1.0  2.0  3.0  4.0
1  0.9  1.9  2.9  3.9
2  0.8  1.8  2.8  3.8
3  0.7  1.7  2.7  3.7

In [15]:
k,details = pyrankability.rank.solve(D,method='hillside')
P = np.array(details['P'][0])
P


array([0, 1, 2, 3])

In [27]:
C = pyrankability.common.compute_C(D.values)
pd.DataFrame(C)

0    1    2    3
0  0.0  0.0  0.0  0.0
1  8.0  0.0  0.0  0.0
2  8.0  8.0  0.0  0.0
3  8.0  8.0  8.0  0.0

In [26]:
np.sum(C)

48.0

In [25]:
n = len(D)
(n*n-n)/2 * 2*n

48.0

In [17]:
direct_thres = 2
spread_thres = 2
weight_indirect = 0

map_func = lambda linked: pyrankability.construct.support_map_vectorized_direct_indirect_weighted(linked,direct_thres=direct_thres,spread_thres=spread_thres,weight_indirect=weight_indirect)
D = pyrankability.construct.V_count_vectorized(game_df,map_func)

assert sum(D.stack()) < len(game_df)

In [19]:
direct_thres = 2
spread_thres = 2
weight_indirect = 0.5

map_func = lambda linked: pyrankability.construct.support_map_vectorized_direct_indirect_weighted(linked,direct_thres=direct_thres,spread_thres=spread_thres,weight_indirect=weight_indirect)
D3 = pyrankability.construct.V_count_vectorized(game_df,map_func)

assert sum(D3.stack()) < sum(D2.stack())